#!/bin/sh
# amalgamate.sh - produce a single-file GPTPS build (SQLite-style):
#   gptps.h  : the public header (drop-in)
#   gptps.c  : the whole library concatenated into one translation unit
# and, optionally, one self-contained .c/.h PAIR per add-on.
#
# Usage:  sh tools/amalgamate.sh [OUT_DIR] [--addons all|none|a,b,c] [--list]
#         (default OUT_DIR ./amalgamation; default --addons none)
# Build:  cc -std=c99 gptps.c yourapp.c -lpthread -ldl
#         cc -std=c99 gptps.c gptps_pool.c yourapp.c -lpthread -ldl
#
# WHY ADD-ONS ARE SEPARATE FILES, never appended to gptps.c:
#
#  1. gptps.c must stay BYTE-IDENTICAL for a given release. Its SHA256 is the thing
#     a Dockerfile, a vcpkg portfile or a blog post pins - which was the entire
#     reason for publishing a release artifact at all. If its contents depended on
#     which add-ons you asked for, one release would have N different hashes for one
#     filename and SHA256SUMS would stop meaning anything.
#  2. Add-ons are opt-in by definition ("link only what you use"). Folding the
#     1100-line dashboard into the core file makes every embedded consumer pay for
#     it, and welds <windows.h> and <sys/socket.h> into the core's system-header
#     surface for everyone.
#  3. They must not be merged with EACH OTHER either: every add-on has file-static
#     helpers, and two in one translation unit can collide on a static name. One .c
#     per add-on is the only shape that is safe for every subset - and subsets are
#     the point.
set -e

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

# name|source|header|description   (the table tools/check_addon_coverage.sh holds to
# the directory listing, so a new add-on cannot silently miss the amalgamation)
ADDONS="await|gptps_await.c|gptps_await.h|blocking wait(handle) on the observer seam
durable_queue|gptps_durable_queue.c|gptps_durable_queue.h|crash-durable submission journal
gpu_quota|gptps_gpu_quota.c|gptps_gpu_quota.h|named-resource admission quota
orch|gptps_orch.c|gptps_orch.h|run-after / fan-in orchestration
pool|gptps_pool.c|gptps_pool.h|N-shard engine router (scale-up)
remote|gptps_remote.c|gptps_remote.h|remote wire codec (cross-host transport)
tui|gptps_tui.c|gptps_tui.h|real-time terminal dashboard
wasm_exec|gptps_wasm_exec.c|gptps_wasm_exec.h|module-as-task, pluggable runtime
xport|gptps_xport.c|gptps_xport.h|worker-process transport (scale-out; POSIX)"

OUT=""
WANT="none"
while [ $# -gt 0 ]; do
    case "$1" in
        --list)    printf '%s\n' "$ADDONS" | cut -d'|' -f1; exit 0 ;;
        --addons)  WANT="$2"; shift 2 ;;
        --addons=*) WANT="${1#--addons=}"; shift ;;
        -*)        echo "unknown option: $1" >&2; exit 2 ;;
        *)         OUT="$1"; shift ;;
    esac
done
OUT=${OUT:-"$ROOT/amalgamation"}
mkdir -p "$OUT"

# Resolve the selection, rejecting a typo rather than silently emitting nothing -
# the same fail-closed lesson the CMake selector and the CI exclude lists encode.
ALL=$(printf '%s\n' "$ADDONS" | cut -d'|' -f1)
case "$WANT" in
    all)  SEL="$ALL" ;;
    none) SEL="" ;;
    *)    SEL=$(printf '%s' "$WANT" | tr ',' ' ')
          for a in $SEL; do
              printf '%s\n' "$ALL" | grep -qx "$a" || {
                  echo "amalgamate.sh: unknown add-on '$a'. Known: $(echo $ALL)" >&2; exit 2; }
          done ;;
esac

# The generated files are the DISTRIBUTED form of GPTPS - for many consumers the
# only form they ever see. LICENSE requires its notice "in all copies or
# substantial portions of the Software", so both outputs carry the full text
# rather than relying on a LICENSE file that does not travel with a two-file
# drop-in. Corporate OSS-intake scanners fail closed on source with no notice.
emit_license() {
    echo "/*"
    sed 's/^/ * /; s/[[:space:]]*$//' "$ROOT/LICENSE"
    echo " */"
    echo "/* SPDX-License-Identifier: MIT */"
}

# public header ships as-is, with the notice prepended
{ emit_license; cat "$ROOT/include/gptps.h"; } > "$OUT/gptps.h"

# Concatenate internal headers + sources into one TU. Strip local quote-includes
# (their contents are inlined here in dependency order); keep <system> includes.
# Both HAL/executor backends are included; each is guarded (#if [!]defined(_WIN32))
# so exactly one compiles per platform -> the single file builds on POSIX AND Windows.
FILES="include/gptps_hal.h src/gptps_internal.h src/alloc.c src/hal_posix.c src/hal_win.c src/config.c src/config_toml.c src/settings.c src/engine.c src/exec_oop_posix.c src/exec_win.c"

{
    emit_license
    echo "/* GPTPS amalgamation - generated by tools/amalgamate.sh; do not edit. */"
    echo "/* Build: cc -std=c99 gptps.c yourapp.c -lpthread -ldl   (macOS: drop -ldl) */"
    echo "/* feature-test macros first, so a plain -std=c99 still exposes POSIX APIs */"
    echo "#if defined(__linux__) && !defined(_GNU_SOURCE)"
    echo "#  define _GNU_SOURCE"
    echo "#endif"
    echo "#if defined(__APPLE__) && !defined(_DARWIN_C_SOURCE)"
    echo "#  define _DARWIN_C_SOURCE"
    echo "#endif"
    echo '#include "gptps.h"'
    for f in $FILES; do
        echo ""
        echo "/* ================= $f ================= */"
        grep -v '^[[:space:]]*#include "' "$ROOT/$f"
    done
} > "$OUT/gptps.c"

echo "amalgamation written:"
echo "  $OUT/gptps.h"
echo "  $OUT/gptps.c  ($(wc -l < "$OUT/gptps.c" | tr -d ' ') lines)"

# --- one self-contained pair per selected add-on ---------------------------
# The header ships verbatim: its #include "gptps.h" still resolves, because gptps.h
# lands right beside it. The source ships verbatim EXCEPT that addon_compat.h is
# inlined at exactly the point it was included - that header is internal, is
# deliberately never installed, and must not become a third file to fetch.
#
# Inlining IN PLACE rather than at the top is load-bearing: every add-on defines its
# feature-test macros (_POSIX_C_SOURCE, _GNU_SOURCE) ABOVE that include, and those
# have to stay first or the POSIX declarations they expose vanish.
for a in $SEL; do
    row=$(printf '%s\n' "$ADDONS" | grep "^$a|")
    src=$(printf '%s' "$row" | cut -d'|' -f2)
    hdr=$(printf '%s' "$row" | cut -d'|' -f3)

    { emit_license
      echo "/* GPTPS add-on amalgamation - generated by tools/amalgamate.sh; do not edit. */"
      cat "$ROOT/addons/$hdr"
    } > "$OUT/$hdr"

    { emit_license
      echo "/* GPTPS add-on amalgamation - generated by tools/amalgamate.sh; do not edit. */"
      echo "/* Build: cc -std=c99 gptps.c $src yourapp.c -lpthread -ldl */"
      awk -v compat="$ROOT/addons/addon_compat.h" '
        /^[[:space:]]*#[[:space:]]*include[[:space:]]*"addon_compat\.h"/ {
            print "/* ---- addons/addon_compat.h (inlined; internal, never installed) ---- */"
            while ((getline l < compat) > 0)
                if (l !~ /^[[:space:]]*#[[:space:]]*include[[:space:]]*"/) print l
            close(compat); next
        }
        { print }' "$ROOT/addons/$src"
    } > "$OUT/$src"

    echo "  $OUT/$src  + $OUT/$hdr"
done
