#!/bin/sh
# amalgamate.sh - produce a single-file GPTPS build (SQLite-style):
#   gptps.h  : the public header (drop-in)
#   gptps.c  : the whole library concatenated into one translation unit
# Usage:  sh tools/amalgamate.sh [OUT_DIR]   (default: ./amalgamation)
# Build:  cc -std=c99 gptps.c yourapp.c -lpthread -ldl
set -e

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
OUT=${1:-"$ROOT/amalgamation"}
mkdir -p "$OUT"

# The generated files are the DISTRIBUTED form of GPTPS - for many consumers the
# only form they ever see. LICENSE requires its notice "in all copies or
# substantial portions of the Software", so both outputs carry the full text
# rather than relying on a LICENSE file that does not travel with a two-file
# drop-in. Corporate OSS-intake scanners fail closed on source with no notice.
emit_license() {
    echo "/*"
    sed 's/^/ * /; s/[[:space:]]*$//' "$ROOT/LICENSE"
    echo " */"
    echo "/* SPDX-License-Identifier: MIT */"
}

# public header ships as-is, with the notice prepended
{ emit_license; cat "$ROOT/include/gptps.h"; } > "$OUT/gptps.h"

# Concatenate internal headers + sources into one TU. Strip local quote-includes
# (their contents are inlined here in dependency order); keep <system> includes.
# Both HAL/executor backends are included; each is guarded (#if [!]defined(_WIN32))
# so exactly one compiles per platform -> the single file builds on POSIX AND Windows.
FILES="include/gptps_hal.h src/gptps_internal.h src/alloc.c src/hal_posix.c src/hal_win.c src/config.c src/config_toml.c src/settings.c src/engine.c src/exec_oop_posix.c src/exec_win.c"

{
    emit_license
    echo "/* GPTPS amalgamation - generated by tools/amalgamate.sh; do not edit. */"
    echo "/* Build: cc -std=c99 gptps.c yourapp.c -lpthread -ldl   (macOS: drop -ldl) */"
    echo "/* feature-test macros first, so a plain -std=c99 still exposes POSIX APIs */"
    echo "#if defined(__linux__) && !defined(_GNU_SOURCE)"
    echo "#  define _GNU_SOURCE"
    echo "#endif"
    echo "#if defined(__APPLE__) && !defined(_DARWIN_C_SOURCE)"
    echo "#  define _DARWIN_C_SOURCE"
    echo "#endif"
    echo '#include "gptps.h"'
    for f in $FILES; do
        echo ""
        echo "/* ================= $f ================= */"
        grep -v '^[[:space:]]*#include "' "$ROOT/$f"
    done
} > "$OUT/gptps.c"

echo "amalgamation written:"
echo "  $OUT/gptps.h"
echo "  $OUT/gptps.c  ($(wc -l < "$OUT/gptps.c" | tr -d ' ') lines)"
