#!/bin/sh
# amalgamate.sh - produce a single-file GPTPS build (SQLite-style):
#   gptps.h  : the public header (drop-in)
#   gptps.c  : the whole library concatenated into one translation unit
# Usage:  sh tools/amalgamate.sh [OUT_DIR]   (default: ./amalgamation)
# Build:  cc -std=c99 gptps.c yourapp.c -lpthread -ldl
set -e

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
OUT=${1:-"$ROOT/amalgamation"}
mkdir -p "$OUT"

# public header ships as-is
cp "$ROOT/include/gptps.h" "$OUT/gptps.h"

# Concatenate internal headers + sources into one TU. Strip local quote-includes
# (their contents are inlined here in dependency order); keep <system> includes.
# POSIX backend today; a Windows backend (hal_win.c/exec_oop_win.c) would be
# guarded and appended here once it exists.
FILES="include/gptps_hal.h src/gptps_internal.h src/hal_posix.c src/config.c src/engine.c src/exec_oop_posix.c"

{
    echo "/* GPTPS amalgamation - generated by tools/amalgamate.sh; do not edit. */"
    echo "/* Build: cc -std=c99 gptps.c yourapp.c -lpthread -ldl   (macOS: drop -ldl) */"
    echo "/* feature-test macros first, so a plain -std=c99 still exposes POSIX APIs */"
    echo "#if defined(__linux__) && !defined(_GNU_SOURCE)"
    echo "#  define _GNU_SOURCE"
    echo "#endif"
    echo "#if defined(__APPLE__) && !defined(_DARWIN_C_SOURCE)"
    echo "#  define _DARWIN_C_SOURCE"
    echo "#endif"
    echo '#include "gptps.h"'
    for f in $FILES; do
        echo ""
        echo "/* ================= $f ================= */"
        grep -v '^[[:space:]]*#include "' "$ROOT/$f"
    done
} > "$OUT/gptps.c"

echo "amalgamation written:"
echo "  $OUT/gptps.h"
echo "  $OUT/gptps.c  ($(wc -l < "$OUT/gptps.c" | tr -d ' ') lines)"
